name: PR Checks

on:
  pull_request:

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          cache: "yarn"
      - run: yarn install
      - name: Run prettier
        run: yarn check-format
