name: Update Status Page

on:
  workflow_dispatch:
    inputs:
      install:
        description: "App Installation"
        type: boolean
        required: true
        default: true
      repo:
        description: "Repository Review"
        type: boolean
        required: true
        default: true
      pr:
        description: "Pull Request Review"
        type: boolean
        required: true
        default: true
      command:
        description: "Comment Commands"
        type: boolean
        required: true
        default: true

jobs:
  update:
    name: Update status page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install EJS
        run: npm install -g ejs
      - name: Render template
        run: ejs ./src/pages/status.ejs install=${{ inputs.install }} repo=${{ inputs.repo }} pr=${{ inputs.pr }} command=${{ inputs.command }} -o ./src/pages/status.md
      - name: Commit files
        run: |
          git config --local user.name "{{ github.triggering_actor }}"
          git commit -a -m "Update status page"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
